platform :ios, '12.0'

target 'TOSMBClientPodTest' do
  # pod 'TOSMBClient', :path => '../'
  # pod 'libdsm', :path => '../TOSMBClient/libdsm/'
  # pod 'libtasn1', :path => '../TOSMBClient/libdsm/libtasn1/'
  
  pod 'TOSMBClient', :git => 'git@github.com:everappz/TOSMBClient.git', :commit => '5a994676016e043dd61abc20b4225d9e2401f2f5'
  pod 'libdsm', :git => 'git@github.com:everappz/libdsm.git', :commit => '8668e22c75681951428258f99bf78fcff1febd8b'
  pod 'libtasn1', :git => 'git@github.com:everappz/libtasn1.git', :commit => '4e28d24967c5f12343341096bcf27203f498b547'
end
